#!/usr/bin/env bash

# sdk_segment

[[ -z ${PL_SYMBOLS[sdk]} ]] && PL_SYMBOLS[sdk]=''

function sdk_segment {
    if [ -n "$ACTIVE_SDK" ]; then
        local sdk="${ACTIVE_SDK##*/}"
        local bg_color="$1"
        local fg_color="$2"
        local content=" ${PL_SYMBOLS[sdk]}$sdk"
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content ")"
        __last_color="$bg_color"
    fi
}
